{% set name = "kipoi_veff2" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: "/Users/b260/code/src/github.com/haimasree/kipoi-veff2"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv "

requirements:
  host:
    - pip
    - python 3.6
    - tensorflow 1.4.*
    - dataclasses 0.8.*
    - h5py 2.10.*
    - keras 2.2.*
    - pytorch 1.3.*
    - numpy 1.18.*
    - pandas 1.1.*
    - cyvcf2 0.30.*
    - bedtools 2.30.*
    - pybedtools 0.8.*
    - torchvision 0.4.*
    - torchaudio 0.3.*
    - click
    - pytest
    - kipoi
    - kipoiseq
    - mmsplice
  run:
    - python 3.6
    - tensorflow 1.4.*
    - dataclasses 0.8.*
    - h5py 2.10.*
    - keras 2.2.*
    - pytorch 1.3.*
    - numpy 1.18.*
    - pandas 1.1.*
    - cyvcf2 0.30.*
    - cython 0.29.*
    - bedtools 2.30.*
    - pybedtools 0.8.*
    - torchvision 0.4.*
    - torchaudio 0.3.*
    - click
    - pytest  
    - kipoi
    - kipoiseq
    - mmsplice
test:
  imports:
    - kipoi_veff2 