name: kipoi-veff2 

on: [push]

jobs:
  build-and-test-package:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies and test
      run: |
        conda env create -f environment.yml 
        source $CONDA/bin/activate kipoi-veff2
        pytest --disable-warnings 